name: Build and Release APK
on: push
jobs:
  hosting:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - uses: actions/checkout@v3

      # Install Flutter command
      - uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.13.0

      # Build Website
      - name: Build Website
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release
        working-directory: ./

      # Decode and store the GCP_SA_KEY
      - name: Decode GCP_SA_KEY
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > /opt/gcp_key.json

      # Deploy Firebase Hosting
      - name: Deploy Firebase Hosting
        uses: w9jds/firebase-action@v13.2.1
        with:
          args: deploy --only hosting:schoolmanagement-703cc
        env:
          GCP_SA_KEY: /opt/gcp_key.json
