jobs:
  hosting:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Google Cloud authentication
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > /opt/gcp_key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/opt/gcp_key.json" >> $GITHUB_ENV

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Firebase Hosting
        run: firebase deploy --only hosting --project schoolmanagement-703cc
